### PR TITLE
CTCP-998: Update JSON schema

### PR DESCRIPTION
**Pull request by drnaylor-oc**
Updated the Json schema to tighten up the validation.

### CODE REVIEW

**Comment by drnaylor-oc** [comment]
This just needs to be checked a little more, but it seems to work with CC015C and CC014C.

**Comment by drnaylor-oc** [comment]
Actually, I'm not sure I like that I've somehow made the test cases smaller - I'm just gonna look into that.

**Review by derekspalmer — DISMISSED** [review]
Some fields have been removed from the JSON: was there a reason for doing this?

**Comment by drnaylor-oc** [comment]
I realised that I'd done that, and I wasn't happy, so I've been through it to fix the regexes. The JSON files in the version you checked were based on the XML files that were used in the tests here.

It's interesting that tightening the schema caused these errors, but there we are.

**Review by derekspalmer — APPROVED** [review]

**Pull request merged**
