### PR TITLE
CTCP-261 Updating readme for the PRA

### PR DESCRIPTION
**Pull request by ardwalker**

### CODE REVIEW

**Review by liandra-giacomine — DISMISSED** [review]

**Comment by drnaylor-oc** [comment]
I'm not sure if this the right thing to put into readmes - almost all of those links are internal or point to private repos and so aren't really appropriate for public consumption.

Should the readme look something more like our other internal services, such as https://github.com/hmrc/transit-movements-trader-at-destination?

**Comment by ardwalker** [comment]
> I'm not sure if this the right thing to put into readmes - almost all of those links are internal or point to private repos and so aren't really appropriate for public consumption.
> 
> Should the readme look something more like our other internal services, such as https://github.com/hmrc/transit-movements-trader-at-destination?

I thought validator was an internal only repo? Let me know what you'd like me to do. 
Thanks!

**Comment by drnaylor-oc** [comment]
It's a public repo, others can spin this up and play with it if they so wish, so the readme should be sensible for anyone from outside HMRC viewing it. 

The running service itself is internal - it's called from the public API service.

**Comment by ardwalker** [comment]
> The README generally needs to explain
> 
> * what the service is and which problem it solves - at a high level.
> * perhaps add endpoints
> * and how to spin the service up.
> * That should be it really.
> * I would leave it as standalone and not reference other services, as they might change in the future and so make our docs erroneous.

What changes are you recommending @derekspalmer?

**Review by RobertLaverick — APPROVED** [review]

**Pull request merged**
